### ISSUE TITLE
It doesn´t work

### ISSUE THREAD

**Issue by roberdebux** [infeeeee/kimai2-cmd-rainmeter#2] opened 2020-04-09 18:55 UTC
Hi.
It doesn´t work for me with Windows 10 O.S.
I installed it correctly, and I can configure my server, username and API password the first time with cmd, but then, when I choose some options like start new measurement or list projects or other command nothing happens. And if I restart the skin the skin shows again "Click KIM to setup".
Please help

**Comment by infeeeee** [comment] 2020-04-10 11:20
Hello
Thank you for your bug report, but I need some more information to help.

After you set up the credentials, it should show where it saved your settings.ini file:
![kép](https://user-images.githubusercontent.com/1271737/78986167-ecce3000-7b2a-11ea-974d-574fb2a16354.png)
Does this path shows up? 

The skin should create this settings.ini file here: `Documents\Rainmeter\Skins\kimai2-cmd-rainmeter\@Resources\kimai2-cmd\settings.ini`. Does this file exist?

Also please enable verbose output this way, and upload the output here: 
- Open this file with a text editor: `Documents\Rainmeter\Skins\kimai2-cmd-rainmeter\kimai2\kimaiMeasures.inc`
- In the `[MeasureFirstrun]` section (line 45) add a `-v` at the end of the Parameter line after a space. This section should look like this:
``` ini
[MeasureFirstrun]
Measure=Plugin
Plugin=RunCommand
Parameter=start "" #kimaiExe# -v
StartInFolder=#kimaiDir#
State=Show
```
- Save this file, in rainmeter reload all, click on the KIM button again, and after you set up create a screenshot, or copy everything from the command prompt window. Blur your credentials or use the demo server as I did in my screenshot.

**Comment by roberdebux** [comment] 2020-04-10 18:26
![2020-04-10_20-18-19](https://user-images.githubusercontent.com/63422277/79013338-cf1fbb80-7b68-11ea-8c5e-82f00d0aa36b.png)
Thank you for your response.
I attached the output from cmd. After this screenshot the cmd was closed by itself and it didn´t show anything. As I said, the skin is showing again "Click KIM to setup" and If I click in STOP or Reload button nothing happens.

**Comment by infeeeee** [comment] 2020-04-11 09:55
It should show "Click KIM to setup" until the first successful call to the server, so this is expected. 

It seems that it calls your server, but no response arrives. 

Please do the following, to find the cause of this:

- Make sure your api access is working: open this site in your browser: `https://kimai.yourserver.com/api/doc`. You should get the same site as on the demo install: https://demo.kimai.org/api/doc . If you get some error, there is some problem with your webserver configuration.

- If you can access your api doc: start a cmd window, and cd to the folder of kimai2-cmd. It should be here: `Documents\Rainmeter\Skins\kimai2-cmd-rainmeter\@Resources\kimai2-cmd`. do some request in verbose mode like this: `kimai2-cmd.exe -v list-recent`, and copy the output here. It's important to start this from a cmd window, in that case it will show the error code before collapsing.

**Comment by roberdebux** [comment] 2020-04-11 17:07
I can access correctly to the webpage, about the point 1.
About the 2nd point, this is the output:
![2020-04-11_19-03-57](https://user-images.githubusercontent.com/63422277/79050046-b4f8e280-7c27-11ea-9792-bd4d7f328f56.png)

**Comment by infeeeee** [comment] 2020-04-11 17:30
It seems like a webserver setup issue, you have a similar problem as in this issue: https://github.com/infeeeee/kimai2-cmd/issues/10

Your webserver returns a html page instead of a json response. 

You can also see this in action if you open the url in your browser. You should get a json string wrapped in curly brackets, like on the demo install, but you will get some http error code or the kimai login page I guess. Compare it what you get on the demo site: https://demo.kimai.org/api/timesheets/recents

Read more about how to set up your webserver in the kimai docs: https://www.kimai.org/documentation/webserver-configuration.html

I will close the issue, as it has nothing to do with kimai2-cmd-rainmeter nor with kimai2-cmd. You can still comment if you have any more questions, and please reply if you figured it out!

**Closed as completed by infeeeee** 2020-04-11 17:30 UTC
